name: Hello World on Self-Hosted Runner

on: 
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: create a file
        run: echo "Hello, World!" > hello.txt
